TOP=..

MAN5=	build.common.mk.5 \
	build.den.mk.5 \
	build.dep.mk.5 \
	build.lib.mk.5 \
	build.prog.mk.5 \
	build.proj.mk.5

include ${TOP}/Makefile.config
include ${TOP}/mk/build.man.mk
include ${TOP}/mk/build.subdir.mk
