TOP=..

MAN1=	mkify.1 \
	mkconfigure.1 \
	mlproc.1

MAN5=	build.common.mk.5 \
	build.lib.mk.5 \
	build.man.mk.5 \
	build.prog.mk.5 \
	build.www.mk.5

include ${TOP}/Makefile.config
include ${TOP}/mk/build.man.mk
include ${TOP}/mk/build.subdir.mk
