# Public domain
# vim:ts=4

my $testCode = << 'EOF';
#include <stdio.h>

#include <agar/core.h>
#include <agar/gui.h>

static const struct {
	const char *name;
	unsigned    value;
} constants[] = {
	{ "AG_GRAPH_LABEL_MAX",		AG_GRAPH_LABEL_MAX },		/* graph.h */
	{ "AG_LABEL_MAX",			AG_LABEL_MAX },				/* label.h */
	{ "AG_LABEL_MAX_POLLPTRS",	AG_LABEL_MAX_POLLPTRS },	/* label.h */
	{ "AG_NOTEBOOK_LABEL_MAX",	AG_NOTEBOOK_LABEL_MAX },	/* notebook.h */
	{ "AG_STATUSBAR_MAX_LABELS",AG_STATUSBAR_MAX_LABELS },	/* statusbar.h */
	{ "AG_STYLE_VALUE_MAX",		AG_STYLE_VALUE_MAX },		/* stylesheet.h */
	{ "AG_TABLE_TXT_MAX",		AG_TABLE_TXT_MAX },			/* table.h */
	{ "AG_TABLE_FMT_MAX",		AG_TABLE_FMT_MAX },			/* table.h */
	{ "AG_TABLE_COL_NAME_MAX",	AG_TABLE_COL_NAME_MAX },	/* table.h */
	{ "AG_TABLE_HASHBUF_MAX",	AG_TABLE_HASHBUF_MAX },		/* table.h */
	{ "AG_TEXT_STATES_MAX",		AG_TEXT_STATES_MAX },		/* text.h */
	{ "AG_TLIST_LABEL_MAX",		AG_TLIST_LABEL_MAX },		/* tlist.h */
	{ "AG_TOOLBAR_MAX_ROWS",	AG_TOOLBAR_MAX_ROWS },		/* toolbar.h */
	{ "AG_WINDOW_CAPTION_MAX",	AG_WINDOW_CAPTION_MAX },	/* window.h */
};

static const struct {
	const char *name;
	size_t      size;
} nonobject_types[] = {
	{ "AG_Surface",				sizeof(AG_Surface) },			/* surface.h */
	{ "AG_AnimFrame",			sizeof(AG_AnimFrame) },			/* surface.h */
	{ "AG_Palette",				sizeof(AG_Palette) },			/* surface.h */
	{ "AG_PixelFormat",			sizeof(AG_PixelFormat) },		/* surface.h */
	{ "AG_Rect",				sizeof(AG_Rect) },				/* geometry.h */
	{ "AG_Color",				sizeof(AG_Color) },				/* colors.h */
	{ "AG_ConsoleLine",			sizeof(AG_ConsoleLine) },		/* console.h */
	{ "AG_EditableBuffer",		sizeof(AG_EditableBuffer) },	/* editable.h */
	{ "AG_EditableClipboard",	sizeof(AG_EditableClipboard) },
	{ "AG_FileOption",			sizeof(AG_FileOption) },		/* file_dlg.h */
	{ "AG_FileType",			sizeof(AG_FileType) },
	{ "AG_FixedPlotterItem",	sizeof(AG_FixedPlotterItem) },	/* fixed_plotter.h */
	{ "AG_GraphVertex",			sizeof(AG_GraphVertex) },		/* graph.h */
	{ "AG_GraphEdge",			sizeof(AG_GraphEdge) },
	{ "AG_StaticIcon",			sizeof(AG_StaticIcon) },		/* iconmgr.h */
	{ "struct ag_keycode",		sizeof(struct ag_keycode) },	/* keymap.h */
	{ "struct ag_key_composition", sizeof(struct ag_key_composition) },
	{ "struct ag_key_mapping",	sizeof(struct ag_key_mapping) },
	{ "AG_MenuItem",			sizeof(AG_MenuItem) },			/* menu.h */
	{ "AG_RadioItem",			sizeof(AG_RadioItem) },			/* radio.h */
	{ "AG_TablePopup",			sizeof(AG_TablePopup) },		/* table.h */
	{ "AG_TableCell",			sizeof(AG_TableCell) },
	{ "AG_TableBucket",			sizeof(AG_TableBucket) },
	{ "AG_TableCol",			sizeof(AG_TableCol) },
	{ "AG_FontSpec",			sizeof(AG_FontSpec) },			/* text.h */
	{ "AG_Glyph",				sizeof(AG_Glyph) },
	{ "AG_TextState",			sizeof(AG_TextState) },
	{ "AG_StaticFont",			sizeof(AG_StaticFont) },
	{ "AG_TextMetrics",			sizeof(AG_TextMetrics) },
	{ "AG_GlyphCache",			sizeof(AG_GlyphCache) },
	{ "AG_CachedText",			sizeof(AG_CachedText) },		/* text_cache.h */
	{ "AG_TextCacheBucket",		sizeof(AG_TextCacheBucket) },
	{ "AG_TlistPopup",			sizeof(AG_TlistPopup) },		/* tlist.h */
	{ "AG_TlistItem",			sizeof(AG_TlistItem) },
	{ "AG_TlistItemQ",			sizeof(AG_TlistItemQ) },
	{ "AG_TreetblCol",			sizeof(AG_TreetblCol) },		/* treetbl.h */
	{ "AG_TreetblRowQ",			sizeof(AG_TreetblRowQ) },
	{ "AG_TreetblCell",			sizeof(AG_TreetblCell) },
	{ "AG_TreetblRow",			sizeof(AG_TreetblRow) },
	{ "AG_Unit",				sizeof(AG_Unit) },				/* units.h */
	{ "AG_SizeReq",				sizeof(AG_SizeReq) },			/* widget.h */
	{ "AG_SizeAlloc",			sizeof(AG_SizeAlloc) },
	{ "AG_FlagDescr",			sizeof(AG_FlagDescr) },
	{ "AG_Action",				sizeof(AG_Action) },
	{ "AG_ActionTie",			sizeof(AG_ActionTie) },
	{ "AG_RedrawTie",			sizeof(AG_RedrawTie) },
	{ "AG_CursorArea",			sizeof(AG_CursorArea) },
	{ "AG_WidgetGL",			sizeof(AG_WidgetGL) },
	{ "AG_WidgetPalette",		sizeof(AG_WidgetPalette) },
	{ "AG_WidgetPvt",			sizeof(AG_WidgetPvt) },
	{ "AG_WindowPvt",			sizeof(AG_WindowPvt) },
};

static void
PrintClass(FILE *f, AG_ObjectClass *C)
{
	AG_ObjectClass *Csub;

	fprintf(f, "# %s [%s]: %u.%u%s%s\n", C->name, C->hier,
	    C->ver.major, C->ver.minor,
		(C->pvt.libs[0] != '\0') ? " @" : "", C->pvt.libs);
	fprintf(f, "%s:%lu\n", C->name, (unsigned long)C->size);

	AG_TAILQ_FOREACH(Csub, &C->pvt.sub, pvt.subclasses)
		PrintClass(f, Csub);
}

int
main(int argc, char *argv[])
{
	AG_AgarVersion ver;
	AG_CPUInfo cpuinfo;
	unsigned int i;
	FILE *f;

	if ((f = fopen("agar.types", "w")) == NULL) {
		printf("Cannot write agar.types\n");
		return (1);
	}

	AG_InitCore("conf-test", 0);
	if (AG_InitGUIGlobals() == -1 ||
	    AG_InitGUI(0) == -1) {
		fclose(f);
		return (1);
	}

	fprintf(f, "# Compiled Agar-GUI type sizes on this system\n#\n");
	fprintf(f, "# This file was generated by the agar.types module of a\n");
	fprintf(f, "# BSDBuild configure script <http://bsdbuild.hypertriton.com>.\n#\n");
	AG_GetVersion(&ver);
	fprintf(f, "# Agar Version %d.%d.%d\n", ver.major, ver.minor, ver.patch);
	AG_GetCPUInfo(&cpuinfo);
	fprintf(f, "# Platform: %s (%s, 0x%x)\n#\n", cpuinfo.arch, cpuinfo.vendorID,
	    cpuinfo.ext);
	fprintf(f, "# Agar-GUI constants\n#\n");
	for (i = 0; i < sizeof(constants) / sizeof(constants[0]); i++)
		fprintf(f, "%s:%u\n", constants[i].name, constants[i].value);

	fprintf(f, "#\n# Size of AG_Object(3) derived classes\n#\n");
	PrintClass(f, &agObjectClass);
		
	fprintf(f, "#\n# Size of other types\n#\n");
	for (i = 0; i < sizeof(nonobject_types) / sizeof(nonobject_types[0]); i++)
		fprintf(f, "%s:%lu\n", nonobject_types[i].name, nonobject_types[i].size);
	
	fclose(f);
	AG_Quit();
	return (0);
}
EOF

sub TEST_agar_types
{
	my ($ver, $pfx) = @_;
	
	MkExecOutputPfx($pfx, 'agar-config', '--version', 'AGAR_VERSION');
	MkIfFound($pfx, $ver, 'AGAR_VERSION');
		MkPrintSN('checking Agar type sizes...');
		MkExecOutputPfx($pfx, 'agar-config', '--cflags', 'AGAR_CFLAGS');
		MkExecOutputPfx($pfx, 'agar-config', '--libs', 'AGAR_LIBS');
		MkCompileAndRunC('HAVE_AGAR_TYPES', '${AGAR_CFLAGS}', '${AGAR_LIBS}',
				         $testCode);
	MkElse;
		DISABLE_agar_types();
	MkEndif;
}

sub DISABLE_agar_types
{
	MkDefine('HAVE_AGAR_TYPES', 'no');
	MkSaveUndef('HAVE_AGAR_TYPES');
}

BEGIN
{
	my $n = 'agar.types';

	$DESCR{$n}   = 'Agar types';
	$URL{$n}     = 'http://libagar.org';

	$TESTS{$n}   = \&TEST_agar_types;
	$DISABLE{$n} = \&DISABLE_agar_types;
	
	$DEPS{$n}    = 'cc';
}
;1
